// vue-extend.d.ts
import { ComponentCustomProperties } from 'vue';
import { VueI18n } from 'vue-i18n';

declare module '@vue/runtime-core' {
    interface ComponentCustomProperties {
        $t: VueI18n['t'];
        $i18n: VueI18n;
    }
}

// [22:29:47.995] Running build in Washington, D.C., USA (East) – iad1 (Hive)
// [22:29:48.091] Cloning github.com/Wa-dot/LalucRelease (Branch: main, Commit: 6e3b099)
// [22:29:48.425] Previous build cache not available
// [22:29:51.651] Cloning completed: 3.560s
// [22:29:51.953] Running "vercel build"
// [22:29:52.389] Vercel CLI 32.4.1
// [22:29:53.028] Installing dependencies...
// [22:29:53.743] npm WARN old lockfile 
// [22:29:53.743] npm WARN old lockfile The package-lock.json file was created with an old version of npm,
// [22:29:53.744] npm WARN old lockfile so supplemental metadata must be fetched from the registry.
// [22:29:53.744] npm WARN old lockfile 
// [22:29:53.744] npm WARN old lockfile This is a one-time fix-up, please be patient...
// [22:29:53.744] npm WARN old lockfile 
// [22:30:01.206] npm WARN deprecated babel@6.23.0: In 6.x, the babel package has been deprecated in favor of babel-cli. Check https://opencollective.com/babel to support the Babel maintainers
// [22:30:01.732] npm WARN deprecated @intlify/vite-plugin-vue-i18n@7.0.0: This plugin support until Vite 3. If you would like to use on Vite 4, please use @intlify/unplugin-vue-i18n
// [22:30:01.978] npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
// [22:30:03.323] 
// [22:30:03.324] added 165 packages in 10s
// [22:30:03.324] 
// [22:30:03.324] 31 packages are looking for funding
// [22:30:03.324]   run `npm fund` for details
// [22:30:03.343] Detected `package-lock.json` generated by npm 7+
// [22:30:03.343] Running "npm run build"
// [22:30:03.773] 
// [22:30:03.773] > laluc@0.0.0 build
// [22:30:03.773] > vue-tsc && vite build
// [22:30:03.773] 
// [22:30:06.781] src/components/FootBar.vue(7,76): error TS2339: Property '$t' does not exist on type '{ $: ComponentInternalInstance; $data: { fb: string; fbIcon: string; insta: string; instaIcon: string; }; $props: { style?: unknown; class?: unknown; key?: string | number | symbol | undefined; ... 8 more ...; onVnodeUnmounted?: VNodeMountHook | ... 1 more ... | undefined; }; ... 10 more ...; $watch<T extends string...'.
// [22:30:06.782] src/components/FootBar.vue(8,68): error TS2339: Property '$t' does not exist on type '{ $: ComponentInternalInstance; $data: { fb: string; fbIcon: string; insta: string; instaIcon: string; }; $props: { style?: unknown; class?: unknown; key?: string | number | symbol | undefined; ... 8 more ...; onVnodeUnmounted?: VNodeMountHook | ... 1 more ... | undefined; }; ... 10 more ...; $watch<T extends string...'.
// [22:30:06.784] src/components/FootBar.vue(9,72): error TS2339: Property '$t' does not exist on type '{ $: ComponentInternalInstance; $data: { fb: string; fbIcon: string; insta: string; instaIcon: string; }; $props: { style?: unknown; class?: unknown; key?: string | number | symbol | undefined; ... 8 more ...; onVnodeUnmounted?: VNodeMountHook | ... 1 more ... | undefined; }; ... 10 more ...; $watch<T extends string...'.
// [22:30:06.785] src/components/FootBar.vue(12,30): error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.
// [22:30:06.785] src/components/FootBar.vue(28,30): error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.
// [22:30:06.785] src/components/NavBar.vue(4,70): error TS2339: Property '$t' does not exist on type '{ $: ComponentInternalInstance; $data: {}; $props: { style?: unknown; class?: unknown; key?: string | number | symbol | undefined; ref?: VNodeRef | undefined; ref_for?: boolean | undefined; ... 6 more ...; onVnodeUnmounted?: 
// I have this errors when I use Vercel to build, but I already fix this in a .d.ts file. However I don't call this file, but that not usefull since .d.ts file are normally call during build. Do u have any advice ?